= Per Anhalter durch das Internet
== Ein Reiseführer für sichere Trips in digitalen Welten

Das Internet ist eine einigermaßen heikle Geschichte. Für das, was aus ihm geworden ist, ist es leider eine Fehlkonstruktion: Was ganz gut funktionierte, als vier amerikanische Universitäten vernetzt wurden, offenbart jede Menge Schwachstellen, wenn Akteure hinzukommen, denen man nicht trauen kann (siehe z.B. Pam, Where World Wide Web Went Wrong). Nun fließt das Internet leider auch noch Großteils durch ein Land, von dem man aller-allerspätestens seit Snowden weiß, dass man besser überhaupt keinem darin mehr trauen sollte: NSA und Obama überwachen alles, Firmen das, was sie in die Hände kriegen. Europäische Volksvertreter reden im besten Fall von Neuland und geben zu, dass sie keine Ahnung haben, wollen im schlimmsten Fall Verschlüsselung verbieten, Vorratsdatenspeicherung einführen und Grundrechtsverletzungen intensivieren, indem sie Kooperationen mit den Kriminellen von der NSA ausbauen.
Dagegen muss man doch etwas tun können, und das kann man, und deshalb gibt es nun den „Anhalter“.
Der „Anhalter“ ist nicht komplett, nicht einmal annähernd komplett: Aus den einzelnen Tipps lässt sich aber vielleicht ein allgemein aufgeklärteres Denken und bedachteres Handeln ableiten.

=== Worum geht es?
Aufgeklärte Internetnutzung, WhatsApp-Deinstallation, Hilfe zum Selbstschutz vor Überwachung, Ausbeutung, Datenkraken.

=== Worum geht es nicht?
Schutz vor kleinkriminellem Kram, Viren, Spam, Browser-Toolbars; Inhaltskompetenz, wie man Sinnvolles zwischen Sami Slimani, Katzen, Bild.de und Spiegel Online findet und sich vor unendlicher Zeitverschwendung schützt, oder wie man echte von falschen Mittelfinger-Videos unterscheidet.

=== Warum SOLLTE ich mich wehren?
Das Internet ist aber nicht nur heikel, sondern auch ziemlich super. Und obwohl es sehr schlimm darum bestellt ist, muss man es nicht aufgeben. Man kann es aber nicht einfach wie es in seiner üblichen Form mit trackenden Websites, WhatsApp, unverschlüsselten Emails, usw. daherkommt nutzen, sondern muss vorher ein paar Anpassungen vornehmen. Die senken meist den Bedienkomfort, teils recht beträchtlich. Aber wir haben uns ja auch daran gewöhnt, die Tür auf dem Klo zuzumachen, bei roter Ampel anzuhalten und Feuerlöscher zu kaufen. Und bei alledem steht weit weniger auf dem Spiel. Wem die Gefahren eines zentral überwachten Internet noch zu diffus sind, der wird an dieser Stelle nicht aufgeklärt werden – der wird George Orwells 1984 lesen oder zumindest mal diese Visualisierung der Vorratsdaten eines Grünen-Politikers auf Zeit.de betrachten müssen.
Kann ich mich der Überwachung komplett entziehen? Nein, nicht, wenn ich Internet und Handy behalten will. Darf ich deshalb komplett auf Gegenmaßnahmen verzichten? Nein:

=== Warum MUSS ich mich wehren?
Weil wir in einer Demokratie leben (sollten). Das Volk ist der Souverän (sollte es sein) und hat damit auch Verantwortung. Demokratie steht im engen Verhältnis zur Aufklärung. Die Aufklärung ist der Ausgang aus der selbst verschuldeten Unmündigkeit, sagt Kant, und
„Unmündigkeit ist das Unvermögen, sich seines Verstandes ohne Leitung eines anderen zu bedienen. Selbstverschuldet ist diese Unmündigkeit, wenn die Ursache derselben nicht am Mangel des Verstandes, sondern der Entschließung und des Mutes liegt, sich seiner ohne Leitung eines anderen zu bedienen. Sapere aude! Habe Mut dich deines eigenen Verstandes zu bedienen!“
Wer das tut, wird sich nicht widerstandslos zum fremdbestimmten Datensatz in den Tabellen von Geheimdiensten, Regierungen, Firmen und Scoring-Systemen machen lassen wollen, die dann ausrechnen, was er kaufen soll, was er lesen soll, ob er ein Terrorist ist und ob er einen Kredit oder einen Job bekommt. Er wird sogar eine Antipathie gegen solcherlei Systeme entwickeln und sich diesen nicht nur entziehen, sondern sie stören, im besten Fall zerstören wollen. Und man kann sie stören: Verschlüsselung soll verboten werden, TOR-Nutzer werden als Terroristen klassifiziert – das bedeutet in erster Linie, dass solche Sachen funktionieren!

=== Also was kann ich nun tun?
Im Folgenden meine ganz persönliche Auswahl an Tools, Nutzungshinweisen usw., die bei einer in obigem Sinn aufgeklärten Internetnutzung helfen können. Es wird nicht alles im Detail beschrieben, das wird an anderer Stelle besser getan als ich es könnte. An diese Stelle wird dann eher verlinkt, sodass man die Lektüre nach eigenem Gutdünken vertiefen kann.

=== Browser:

* RequestPolicy, Ghostery o.Ä. verwenden: Solche Tools verhindern, dass eine Website ungefragt Verbindungen zu weiteren Websites aufbaut (und machen damit mehr als ebenfalls empfehlenswerte Werbe-/Scriptblocker). Das sind Tracker, die Statistiken anlegen (Google Analytics; ivwbox, …), Werbung, Beacons (die etwa Facebook sagen, was man so alles besucht) und vieles mehr. Für Faz.net unterbindet RequestPolicy bspw. 14 Verbindungsversuche, darunter neben üblichem Google/Facebook-Zeug auch Mysteriöses wie yieldlab, plista, krxd, nuggad, t4ft, doubleclick – was auch immer das für Leute sein mögen: benutzt man seinen Browser, wie er ausgeliefert wird, haben sie alle erstmal die Verbindungsdaten des Faz.net-Besuchers, ohne dass er davon erfahren würde. Faz.net ist kein schwarzes Schaf, das ist die Regel (Sueddeutsche.de hat 21 Weiterleitungen).
* TOR (JonDo, VPN): Falls man bei einem Spaziergang im Netz mal nicht Namen und Adresse auf die Stirn tätowiert haben möchte (was angesichts der Omnipräsenz oben beschriebener Machenschaften ja durchaus mal der Fall sein könnte) empfiehlt sich ein Anonymisierungsdienst wie TOR. Hat den Nachteil, dass man von der NSA als Terrorist eingestuft wird. Komplett sicher ist das Ganze auch nicht mehr, schnell schon mal gar nicht, aber gelegentlich immer noch besser als das Tattoo. TOR gibt’s auch für's Telefon mit Orbot+Orweb. Eine Alternative ist etwa JonDo, auch Virtual Private Networks kann man zur Anonymisierung verwenden.
* Regelmäßig Netzpolitik.org lesen


=== Smartphone:

* App-Berechtigungen: Apps teilen in einem Dialog vor der Installation ziemlich genau mit, was sie auf dem Telefon anstellen dürfen. Dieser Dialog ist ziemlich wichtig (auch wenn er bei Google Android neulich bis kurz vor Nutzlosigkeit gekürzt wurde). Wenn Apps komische Berechtigungen verlangen, die für ihre Funktionalität nicht wirklich zentral sind, sollte man sie nicht installieren (Mein aktuelles Problem dazu: Warum möchten so viele Newsreader auf meine Identität zugreifen (etwa Feedity)?).
* Ganz besondere Vorsicht empfiehlt sich ja, wenn eine App das Telefonbuch auslesen möchte. Damit kompromittiere ich nicht nur meine eigene Privatsphäre, sondern die all meiner Kontakte, die nicht unbedingt wollen, dass ihre Handynummer in Verbindung mit Klarnamen bei Hinz und Kunz bekannt wird. Da z.B. WhatsApp genau das will, muss man eigentlich schon im Installationsdialog hängen bleiben. Es selbst zu verweigern ist daher die einzig mögliche aufgeklärte Entscheidung; pragmatisch nützt das aber nichts, da es jeder andere installiert und damit auch Nummern und Klarnamen von Verweigerern längst von 50 anderen Handys ausgelesen worden sind (Google liest das Telefonbuch mit Android übrigens schon von Natur aus, Apple und Microsoft mit Sicherheit ebenfalls).
* Wo wir gerade dabei sind: Konsequente Naturen sollten ihr Smartphone daher rooten/jailbreaken und ein Open Source-Betriebssystem aufspielen. Das Gerät ist, egal wie teuer es war, eher Leihgabe denn eigener Besitz solange iOS, Windows, oder Google Android darauf laufen. Entsprechend ausgeliefert ist man den unbekannten Machenschaften, die diese Betriebssysteme im Hintergrund so vollziehen.
* Wichtige Apps:
** Orbot und Orweb, falls mal anonym gebrowst werden muss
** Ein gescheiter Messenger, z.B. ChatSecure oder was anderes Jabber-mäßiges. Siehe die Secure Message Scorecard
* Zu vermeidende Apps:
** Facebook Messenger; Warum nicht das Webinterface? Klappt doch super im Mobilbrowser
** Alles, was das Telefonbuch auslesen möchte (also WhatsApp)
** Alles, was seltsame Berechtigungen einfordert
* Und etwas Handfestes: Viele kleben vernünftigerweise die Webcam an ihrem Laptop ab. Abgeklebte Frontkameras an Smartphones sieht man dagegen selten, empfehlen sich aber vorsichtshalber auch.


=== Software allgemein:

* Open fucking Source: Das kann man gar nicht laut und oft genug betonen, siehe Richard Stallman. Ich kann keiner Software vertrauen, deren Quelltext nicht offen ist. WhatsApp Verschlüsselt jetzt, iMessage auch? Das nützt leider überhaupt nichts, denn niemand weiß, ob alles sauber implementiert ist, ob nicht doch wieder Hintertürchen für NSA & Co eingebaut wurden, ob der Hersteller selbst nicht doch mitlesen kann. Nur durch öffentliche Überprüfbarkeit kann so etwas ausgeschlossen bzw. zumindest sehr schnell erkannt werden. Daher ist auch Threema als WhatsApp-Alternative eine inkonsequente Wahl.
* Das gilt natürlich insbesondere für so etwas Wichtiges wie das Betriebssystem: Windows oder MacOS sollten angesichts leicht zu verwender Linux-Varianten wie Ubuntu oder freien auf mit Blick auf Privatsphäre optimierten Systemen wie Tails gar nicht mehr verwendet werden. Apple-Produkte verbieten sich aufgrund der in den Fabriken herrschenden, immer und immer wieder kritisieren Arbeitsbedingungen sowieso, sofern man kein Freund von Sklavenhaltung ist. Das wäre nebenbei dann auch das Ende des durch inkompatible MS Office-Dateien verursachten Stresses und des unglaublichen Format-Chaos, welches Microsoft da angerichtet hat.
* Diversifikation: Es scheint mir eine schlechte Idee, alle Daten einem Anbieter anzuvertrauen. Gmail, Android, Google Kalender, Google Suche? Damit weiß Google dann unnötigerweise alles. Wenn Android, dann lieber dafür einen ansonsten ungenutzten Google-Account, Mails notfalls bei GMX, Suche bei duckduckgo. Auch Blogartikel etc. kommentiert man besser unabhängig von Facebook-Accounts. Wer meint, eine Cloud zu brauchen, könnte sich etwa ownCloud anschauen. So besteht die Chance, dass das Profil, welches Unternehmen anlegen, recht unvollständig und wenig aussagekräftig bleibt. Die NSA kann sich so auch nicht die kompletten Infos an einer Zentrale abholen.
* Emails verschlüsseln: Empfiehlt sich schon deshalb, weil es Geheimdiensten einfach das Leben ein kleines Stück schwerer macht. Leider ist das Verschlüsseln, etwa mit PGP, nicht ganz trivial. Dafür ist davon auszugehen, dass es, richtig verwendet, sicher ist. Zum Einstieg empfiehlt sich, erstmal Outlook zu deinstallieren und etwa durch Thunderbird zu ersetzen, bspw. mit Enigmail aufzurüsten, und dann auf http://www.openpgp-schulungen.de/kurzinfo/ in die Lektüre einzusteigen.


Leider hat dieser „Anhalter“ gegenüber dem Original von Douglas Adams den enormen Nachteil, keinen Umschlag zu haben, auf dem dann in großen, freundlichen Buchstaben „KEINE PANIK“ stünde. Denn Panik ist bei Reisen im Internet wirklich nicht angebracht, wohl aber eine stete Grundparanoia. Wem der Sprung aus der selbst verschuldeten Unmündigkeit zu anstrengend scheint, der mag die Hinweise des „Anhalter“ getrost in den Wind schießen. Wer sie aber (teilweise) beherzigt, ergänzt, zum Anlass zu weiterer Recherche nimmt, macht große Schritte auf dem Weg zu seiner persönlichen digitalen Aufklärung und leistet einigen ekligen Mechanismen aus Wirtschaft und Politik mindestens passiven Widerstand.
(Danke an Alex für seine ergänzenden Hinweise)