= Überwachungsgesetze: Warum die Verfassung nicht präventiv schützen?

Es wird mal wieder ein demokratiefeindliches Gesetz auf den Weg gebracht: https://netzpolitik.org/2015/neues-verfassungsschutz-gesetz-bnd-will-ueberwachung-zum-gefahrenbereich-cyber-massiv-ausbauen/. Das geschieht gefühlt in solcher Regelmäßigkeit, dass man fast übersieht, wie skandalös solche Forderungen sind und es leider versäumt, die Fordernden schläunigst wegzusperren. Mir drängt sich durch solche Gesetzesentwürfe (und kluge Kommentare unter verlinktem Artikel) aber eine andere Frage auf.

Mir ist nämlich völlig schleierhaft, warum Gesetze wie Obiges, "die vor dem Bundesverfassungsgericht keine Chance hätte[n]" (https://netzpolitik.org/2015/neues-verfassungsschutz-gesetz-bnd-will-ueberwachung-zum-gefahrenbereich-cyber-massiv-ausbauen/[s. Zitat Härting]), erst einmal erlassen werden müssen, bevor man gegen sie klagen kann, und warum dann nach erfolgreicher Klage nicht alle Fürsprecher in den Knast geschickt werden. Diese Gesetzeslage lädt bei Misserfolg zum munteren Herumprobieren ein, siehe die Vorratsdatenspeicherung, die man durch Charlie-Hebdo-Instrumentalisierung wieder in Stellung bringt. Zudem kann es recht lange dauern, so etwas dann durch eine Klage wieder loszuwerden.
Nun ist es mit meinen Jurakenntnissen auch nicht allzu weit her, aber dass man Leute wie Thomas  http://m.spiegel.de/netzwelt/netzpolitik/a-1014244.html#spRedirectedFrom=www&referrrer=["Anti-Verschlüsselung"] de Maziere so nicht arbeiten lassen sollte, scheint mir doch einigermaßen offensichtlich.