= Lichtblicke und Fußtritte

Selten können Datenschützer einmal lächelnd von einem Artikel aufblicken, doch die Niederlande und Bulgarien gaben nun mit ihrem Verbot der Vorratsdatenspeicherung http://www.spiegel.de/netzwelt/netzpolitik/vorratsdatenspeicherung-verbote-in-bulgarien-und-niederlande-a-1023353.html[einen Grund zur Freude].

Wie scharfe Schießhunde sehen deutsche SPD- und CDU-Politiker diesen Widerstand gegen die VDS leider eher als Ansporn, sich neue Tricks auszudenken. Sigmar Gabriel will sie, selbstverständlich will sie http://lobbyplag.eu/governments[Thomas de Maziere]. Durch die Verbote in ihrer juristischen Kreativität beflügelt brachten sie in dieser Woche einen Fußtritt in Form http://www.rp-online.de/politik/deutschland/eugh-urteil-koalition-lotet-kleine-vorratsdatenspeicherung-aus-aid-1.4940505[der kleinen VDS] hervor. Wieder und wieder wird die VDS verboten, warum ist die Reaktion darauf, sie auf Teufel komm raus durchbringen zu wollen? Solche Zähigkeit wünscht man sich bei der Bekämpfung von Rechtsbrüchen (nein, dafür will niemand die VDS!), nicht bei der Begehung.

Das http://dasweissschesammelsurium.de/OOM.html[OOM] war über all das wirklich kein bisschen erfreut und quittierte es sogleich mit einem OOM++.