= OOM glaubt, wahre Identität Sigmar Gabriel enttarnt zu haben

Das wäre ein starkes Stück: Der deutsche Wirtschaftsminister Sigmar Gabriel machte zuletzt mit sehr merkwürdigen http://www.spiegel.de/politik/deutschland/vorratsdatenspeicherung-sigmar-gabriel-von-juso-chefin-kritisiert-a-1023764.html[Äußerungen zur Vorratsdatenspeicherung] und nun der https://netzpolitik.org/2015/bmwi-lobbyist-der-musikindustrie-wird-beauftragter-fuer-digitale-oekonomie/[Ernennung Dieter Gornys zum Beauftragten für Digitale Ökonomie] von sich Reden.

All das konnte dem http://dasweissschesammelsurium.de/OOM.html[Orwell-O-Meter] natürlich nicht entgehen. Angesichts der skurrilen Ereignisse wurden die Algorithmen stutzig, rechneten hin und her und errechneten, dass mit einer Wahrscheinlichkeit von 85,6% in den kommenden Tagen Jan Böhmermann in einem Video zugeben wird, Sigmar Gabriel zu sein. Das Video wird voraussichtlich in einer Art Making Of die langjährige Arbeit seines Maskenbildnerteams am nahezu lebensechten Kostüm darstellen.

Bis sich das allerdings bestätigt, muss trotzdem ein http://dasweissschesammelsurium.de/OOM.html[OOM++] verbucht werden.