= Man höre auf Richard Stallman

Der GNU-Papst Richard Stallman ist ein Prediger - er predigt radikalen Verzicht und wünscht, verlangt geradezu, dass mehr Menschen seiner Philosophie der freien Software folgen. Und obwohl er ein Ideologe ist und sich dadurch in nicht immer leicht verständlichen Hassäußerungen gegenüber open source (dem Label, nicht der Tatsache) im Unterschied zu freier Software (sein eigenes Label) verliert, sollten wir ihm zuhören. Denn sieht man von solchem Heckmeck ab, sagt er enorm wichtige Dinge.

Zentral geht es ihm um die Problematik, dass es Marketingstrategen wie "evil genius" Steve Jobs geschafft haben, dass wir uns bereitwillig von Software in Ketten legen und ausspionieren lassen, dass wir NSA-Hintertüren und jahrelang bekannte, ungefixte Sicherheitslücken hinnehmen, wenn es freie Alternativen gibt.

Im letzten Jahr hielt er den folgenden Vortrag, in dem er viele seiner wegweisenden Ansichten darlegt:

++++
<iframe src="http://media.ccc.de/browse/congress/2014/31c3_-_6123_-_en_-_saal_1_-_201412291130_-_freedom_in_your_computer_and_in_the_net_-_richard_stallman/oembed.html" width="853" height="480" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
++++

Interessant ist auch die Rubrik "What's bad about" seiner Homepage https://www.stallman.org/, wo er begründet, warum man seiner Meinung nach Amazon, Apple, Facebook, Skype Google, Ebooks und mehr meiden sollte.

Man muss seinen Ratschlägen nicht in ihrer ganzen Radikalität folgen (der Mann besitzt kein Handy, verwendet keinen Flash Player und keine .mp3s). Man sollte sie sich aber dennoch durch den Kopf gehen lassen und sich die Frage stellen, ob die Rückgewinnung eigener Freiheit nicht einiges an Komfortverzicht rechtfertigt.